# Konfigurasi Rust MikroTik Gateway

listen = "127.0.0.1:8080"
api_token = "change-me-to-a-long-random-string"

# Router Lokal (Default)
[[router]]
id = "main"
addr = "192.168.88.1:8728"
user = "admin"
password = ""

# Contoh Router Remote via VPN / IP Public (Contoh: ath.vpnbersama.us)
[[router]]
id = "remote_vpn"
addr = "ath.vpnbersama.us:51121"
user = "admin"
password = "isi_password_router_anda"
